// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"database/sql"
)

type Archive struct {
	ID        int64
	Path      string
	Extension sql.NullString
}

type Hash struct {
	ArchiveID int64
	Md5       []byte
	Sha1      []byte
	Sha256    []byte
}

type Note struct {
	ArchiveID int64
	Title     string
	Text      string
}

type PerceptualHash struct {
	ArchiveID int64
	Hashtype  string
	Hash      int64
}

type Tag struct {
	TagID int64
	Text  string
}

type Tagmap struct {
	ArchiveID int64
	TagID     int64
}

type Timestamp struct {
	ArchiveID    int64
	DateModified string
	DateImported string
	DateCreated  string
}
