// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: sqlite-query.sql

package sqlc

import (
	"context"
	"database/sql"
)

const DeleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE text == (?1)
`

func (q *Queries) DeleteTag(ctx context.Context, tag string) error {
	_, err := q.db.ExecContext(ctx, DeleteTag, tag)
	return err
}

const DeleteTagMap = `-- name: DeleteTagMap :exec
DELETE FROM tagmap WHERE tag_id == (?1)
`

func (q *Queries) DeleteTagMap(ctx context.Context, tagID int64) error {
	_, err := q.db.ExecContext(ctx, DeleteTagMap, tagID)
	return err
}

const GetEntry = `-- name: GetEntry :one
SELECT id, path, extension FROM archive WHERE id == (?1)
`

func (q *Queries) GetEntry(ctx context.Context, archiveID int64) (Archive, error) {
	row := q.db.QueryRowContext(ctx, GetEntry, archiveID)
	var i Archive
	err := row.Scan(&i.ID, &i.Path, &i.Extension)
	return i, err
}

const GetEntryPath = `-- name: GetEntryPath :one
SELECT path, extension FROM archive WHERE id == (?1)
`

type GetEntryPathRow struct {
	Path      string
	Extension sql.NullString
}

func (q *Queries) GetEntryPath(ctx context.Context, archiveID int64) (GetEntryPathRow, error) {
	row := q.db.QueryRowContext(ctx, GetEntryPath, archiveID)
	var i GetEntryPathRow
	err := row.Scan(&i.Path, &i.Extension)
	return i, err
}

const GetHashes = `-- name: GetHashes :one
SELECT archive_id, md5, sha1, sha256 FROM hashes WHERE archive_id == (?1)
`

func (q *Queries) GetHashes(ctx context.Context, archiveID int64) (Hash, error) {
	row := q.db.QueryRowContext(ctx, GetHashes, archiveID)
	var i Hash
	err := row.Scan(
		&i.ArchiveID,
		&i.Md5,
		&i.Sha1,
		&i.Sha256,
	)
	return i, err
}

const GetMostRecentArchiveID = `-- name: GetMostRecentArchiveID :one
SELECT id FROM archive ORDER BY ROWID DESC LIMIT 1
`

func (q *Queries) GetMostRecentArchiveID(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, GetMostRecentArchiveID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const GetPerceptualHash = `-- name: GetPerceptualHash :one
SELECT hash FROM perceptual_hashes 
WHERE archive_id == (?1) AND hashtype == (?2)
`

type GetPerceptualHashParams struct {
	ArchiveID int64
	Hashtype  string
}

func (q *Queries) GetPerceptualHash(ctx context.Context, arg GetPerceptualHashParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, GetPerceptualHash, arg.ArchiveID, arg.Hashtype)
	var hash int64
	err := row.Scan(&hash)
	return hash, err
}

const GetTagID = `-- name: GetTagID :one
SELECT tag_id, text FROM tags WHERE text == (?1)
`

func (q *Queries) GetTagID(ctx context.Context, tag string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, GetTagID, tag)
	var i Tag
	err := row.Scan(&i.TagID, &i.Text)
	return i, err
}

const GetTagsFromArchiveID = `-- name: GetTagsFromArchiveID :many
SELECT tags.text FROM tags 
	INNER JOIN tagmap ON tags.tag_id = tagmap.tag_id 
WHERE tagmap.archive_id == (?1)
`

func (q *Queries) GetTagsFromArchiveID(ctx context.Context, archiveID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, GetTagsFromArchiveID, archiveID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var text string
		if err := rows.Scan(&text); err != nil {
			return nil, err
		}
		items = append(items, text)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetTimestamps = `-- name: GetTimestamps :one
SELECT archive_id, date_modified, date_imported, date_created FROM timestamps WHERE archive_id == (?1)
`

func (q *Queries) GetTimestamps(ctx context.Context, archiveID int64) (Timestamp, error) {
	row := q.db.QueryRowContext(ctx, GetTimestamps, archiveID)
	var i Timestamp
	err := row.Scan(
		&i.ArchiveID,
		&i.DateModified,
		&i.DateImported,
		&i.DateCreated,
	)
	return i, err
}

const NewEntry = `-- name: NewEntry :exec
INSERT INTO archive (path, extension) VALUES (?1, ?2)
RETURNING id
`

type NewEntryParams struct {
	Path      string
	Extension sql.NullString
}

func (q *Queries) NewEntry(ctx context.Context, arg NewEntryParams) error {
	_, err := q.db.ExecContext(ctx, NewEntry, arg.Path, arg.Extension)
	return err
}

const NewTag = `-- name: NewTag :exec
INSERT OR IGNORE INTO tags (text) VALUES (?1)
`

func (q *Queries) NewTag(ctx context.Context, tag string) error {
	_, err := q.db.ExecContext(ctx, NewTag, tag)
	return err
}

const RemoveTag = `-- name: RemoveTag :exec
DELETE FROM tagmap
	WHERE tagmap.archive_id == (?1) AND
	tagmap.tag_id IN 
		(SELECT tags.tag_id FROM tags 
			INNER JOIN tagmap ON tags.tag_id = tagmap.tag_id 
				WHERE tags.text == (?2))
`

type RemoveTagParams struct {
	ArchiveID int64
	Text      string
}

func (q *Queries) RemoveTag(ctx context.Context, arg RemoveTagParams) error {
	_, err := q.db.ExecContext(ctx, RemoveTag, arg.ArchiveID, arg.Text)
	return err
}

const SearchTag = `-- name: SearchTag :many
SELECT archive.id, tags.tag_id, tags.text FROM tags 
	INNER JOIN tagmap ON tagmap.tag_id = tags.tag_id
	INNER JOIN archive ON archive.id = tagmap.archive_id
WHERE tags.text == (?1)
`

type SearchTagRow struct {
	ID    int64
	TagID int64
	Text  string
}

func (q *Queries) SearchTag(ctx context.Context, tag string) ([]SearchTagRow, error) {
	rows, err := q.db.QueryContext(ctx, SearchTag, tag)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchTagRow
	for rows.Next() {
		var i SearchTagRow
		if err := rows.Scan(&i.ID, &i.TagID, &i.Text); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SetHashes = `-- name: SetHashes :exec
INSERT OR REPLACE INTO hashes 
	(archive_id, md5, sha1, sha256) 
VALUES (?1, ?2, ?3, ?4)
`

type SetHashesParams struct {
	ArchiveID int64
	Md5       []byte
	Sha1      []byte
	Sha256    []byte
}

func (q *Queries) SetHashes(ctx context.Context, arg SetHashesParams) error {
	_, err := q.db.ExecContext(ctx, SetHashes,
		arg.ArchiveID,
		arg.Md5,
		arg.Sha1,
		arg.Sha256,
	)
	return err
}

const SetPerceptualHash = `-- name: SetPerceptualHash :exec
INSERT OR REPLACE INTO perceptual_hashes
	(archive_id, hashtype, hash)
VALUES (?1, ?2, ?3)
`

type SetPerceptualHashParams struct {
	ArchiveID int64
	Hashtype  string
	Hash      int64
}

func (q *Queries) SetPerceptualHash(ctx context.Context, arg SetPerceptualHashParams) error {
	_, err := q.db.ExecContext(ctx, SetPerceptualHash, arg.ArchiveID, arg.Hashtype, arg.Hash)
	return err
}

const SetTag = `-- name: SetTag :exec
INSERT OR IGNORE INTO tagmap 
	(archive_id, tag_id)
VALUES(?1, (SELECT tag_id FROM tags WHERE text = (?2)))
`

type SetTagParams struct {
	ArchiveID int64
	Tag       string
}

func (q *Queries) SetTag(ctx context.Context, arg SetTagParams) error {
	_, err := q.db.ExecContext(ctx, SetTag, arg.ArchiveID, arg.Tag)
	return err
}

const SetTimestamps = `-- name: SetTimestamps :exec
INSERT OR REPLACE INTO timestamps 
	(archive_id, date_modified, date_imported, date_created)
VALUES (?1, ?2, ?3, ?4)
`

type SetTimestampsParams struct {
	ArchiveID    int64
	DateModified string
	DateImported string
	DateCreated  string
}

func (q *Queries) SetTimestamps(ctx context.Context, arg SetTimestampsParams) error {
	_, err := q.db.ExecContext(ctx, SetTimestamps,
		arg.ArchiveID,
		arg.DateModified,
		arg.DateImported,
		arg.DateCreated,
	)
	return err
}
