// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: archive_query.sql

package archive

import (
	"context"
	"database/sql"
	"strings"
)

const DeleteEntry = `-- name: DeleteEntry :exec
DELETE from archive WHERE id == (?1)
`

func (q *Queries) DeleteEntry(ctx context.Context, archiveID int64) error {
	_, err := q.exec(ctx, q.deleteEntryStmt, DeleteEntry, archiveID)
	return err
}

const DeleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE text == (?1)
`

func (q *Queries) DeleteTag(ctx context.Context, tag string) error {
	_, err := q.exec(ctx, q.deleteTagStmt, DeleteTag, tag)
	return err
}

const DeleteTagMap = `-- name: DeleteTagMap :exec
DELETE FROM tag_map WHERE tag_id == (?1)
`

func (q *Queries) DeleteTagMap(ctx context.Context, tagID int64) error {
	_, err := q.exec(ctx, q.deleteTagMapStmt, DeleteTagMap, tagID)
	return err
}

const GetEntry = `-- name: GetEntry :one
SELECT id, path, extension FROM archive WHERE id == (?1)
`

func (q *Queries) GetEntry(ctx context.Context, archiveID int64) (Archive, error) {
	row := q.queryRow(ctx, q.getEntryStmt, GetEntry, archiveID)
	var i Archive
	err := row.Scan(&i.ID, &i.Path, &i.Extension)
	return i, err
}

const GetEntryPath = `-- name: GetEntryPath :one
SELECT path, extension FROM archive WHERE id == (?1)
`

type GetEntryPathRow struct {
	Path      string
	Extension string
}

func (q *Queries) GetEntryPath(ctx context.Context, archiveID int64) (GetEntryPathRow, error) {
	row := q.queryRow(ctx, q.getEntryPathStmt, GetEntryPath, archiveID)
	var i GetEntryPathRow
	err := row.Scan(&i.Path, &i.Extension)
	return i, err
}

const GetHashes = `-- name: GetHashes :one
SELECT archive_id, md5, sha1, sha256 FROM hashes_chksum WHERE archive_id == (?1)
`

func (q *Queries) GetHashes(ctx context.Context, archiveID int64) (HashesChksum, error) {
	row := q.queryRow(ctx, q.getHashesStmt, GetHashes, archiveID)
	var i HashesChksum
	err := row.Scan(
		&i.ArchiveID,
		&i.Md5,
		&i.Sha1,
		&i.Sha256,
	)
	return i, err
}

const GetMetadata = `-- name: GetMetadata :one
SELECT archive_id, file_size, file_mimetype, media_width, media_height, media_orientation FROM "archive_metadata" WHERE archive_id == (?1)
`

func (q *Queries) GetMetadata(ctx context.Context, archiveID int64) (ArchiveMetadata, error) {
	row := q.queryRow(ctx, q.getMetadataStmt, GetMetadata, archiveID)
	var i ArchiveMetadata
	err := row.Scan(
		&i.ArchiveID,
		&i.FileSize,
		&i.FileMimetype,
		&i.MediaWidth,
		&i.MediaHeight,
		&i.MediaOrientation,
	)
	return i, err
}

const GetMostRecentArchiveID = `-- name: GetMostRecentArchiveID :one
SELECT id FROM archive ORDER BY ROWID DESC LIMIT 1
`

func (q *Queries) GetMostRecentArchiveID(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.getMostRecentArchiveIDStmt, GetMostRecentArchiveID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const GetMostRecentTagID = `-- name: GetMostRecentTagID :one
SELECT tag_id FROM tags ORDER BY ROWID DESC LIMIT 1
`

func (q *Queries) GetMostRecentTagID(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.getMostRecentTagIDStmt, GetMostRecentTagID)
	var tag_id int64
	err := row.Scan(&tag_id)
	return tag_id, err
}

const GetPagesByDateCreated = `-- name: GetPagesByDateCreated :many
SELECT id, path, extension FROM archive 
INNER JOIN archive_timestamps ON archive.id = archive_timestamps.archive_id
ORDER BY archive_timestamps.date_created LIMIT (?2) OFFSET (?1)
`

type GetPagesByDateCreatedParams struct {
	Offset interface{}
	Limit  interface{}
}

func (q *Queries) GetPagesByDateCreated(ctx context.Context, arg GetPagesByDateCreatedParams) ([]Archive, error) {
	rows, err := q.query(ctx, q.getPagesByDateCreatedStmt, GetPagesByDateCreated, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Archive
	for rows.Next() {
		var i Archive
		if err := rows.Scan(&i.ID, &i.Path, &i.Extension); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetPagesByDateImported = `-- name: GetPagesByDateImported :many
SELECT id, path, extension FROM archive 
INNER JOIN archive_timestamps ON archive.id = archive_timestamps.archive_id
ORDER BY archive_timestamps.date_imported LIMIT (?2) OFFSET (?1)
`

type GetPagesByDateImportedParams struct {
	Offset interface{}
	Limit  interface{}
}

func (q *Queries) GetPagesByDateImported(ctx context.Context, arg GetPagesByDateImportedParams) ([]Archive, error) {
	rows, err := q.query(ctx, q.getPagesByDateImportedStmt, GetPagesByDateImported, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Archive
	for rows.Next() {
		var i Archive
		if err := rows.Scan(&i.ID, &i.Path, &i.Extension); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetPagesByDateModified = `-- name: GetPagesByDateModified :many
SELECT id, path, extension FROM archive 
INNER JOIN archive_timestamps ON archive.id = archive_timestamps.archive_id
ORDER BY archive_timestamps.date_modified LIMIT (?2) OFFSET (?1)
`

type GetPagesByDateModifiedParams struct {
	Offset interface{}
	Limit  interface{}
}

func (q *Queries) GetPagesByDateModified(ctx context.Context, arg GetPagesByDateModifiedParams) ([]Archive, error) {
	rows, err := q.query(ctx, q.getPagesByDateModifiedStmt, GetPagesByDateModified, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Archive
	for rows.Next() {
		var i Archive
		if err := rows.Scan(&i.ID, &i.Path, &i.Extension); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetPerceptualHash = `-- name: GetPerceptualHash :one
SELECT hash FROM hashes_perceptual 
WHERE archive_id == (?1) AND hash_type == (?2)
`

type GetPerceptualHashParams struct {
	ArchiveID int64
	HashType  string
}

func (q *Queries) GetPerceptualHash(ctx context.Context, arg GetPerceptualHashParams) (int64, error) {
	row := q.queryRow(ctx, q.getPerceptualHashStmt, GetPerceptualHash, arg.ArchiveID, arg.HashType)
	var hash int64
	err := row.Scan(&hash)
	return hash, err
}

const GetTagCountByList = `-- name: GetTagCountByList :many
SELECT tags.text, count(tags.text) FROM tags 
INNER JOIN tag_map ON tags.tag_id = tag_map.tag_id 
INNER JOIN archive ON tag_map.archive_id = archive.id
WHERE archive.id IN (/*SLICE:archive_ids*/?)
GROUP BY tags.text
ORDER BY count(tags.text) DESC LIMIT (?2)
`

type GetTagCountByListParams struct {
	ArchiveIds []int64
	Limit      interface{}
}

type GetTagCountByListRow struct {
	Text  string
	Count int64
}

func (q *Queries) GetTagCountByList(ctx context.Context, arg GetTagCountByListParams) ([]GetTagCountByListRow, error) {
	query := GetTagCountByList
	var queryParams []interface{}
	if len(arg.ArchiveIds) > 0 {
		for _, v := range arg.ArchiveIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:archive_ids*/?", strings.Repeat(",?", len(arg.ArchiveIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:archive_ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Limit)
	rows, err := q.query(ctx, nil, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTagCountByListRow
	for rows.Next() {
		var i GetTagCountByListRow
		if err := rows.Scan(&i.Text, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetTagCountByRange = `-- name: GetTagCountByRange :many
SELECT tags.text, count(tags.text) FROM tags 
INNER JOIN tag_map ON tags.tag_id = tag_map.tag_id 
WHERE tag_map.archive_id BETWEEN (?1) AND (?2)
GROUP BY tags.text
ORDER BY count(tags.text) DESC 
LIMIT (?4) OFFSET (?3)
`

type GetTagCountByRangeParams struct {
	Start  int64
	End    int64
	Offset interface{}
	Limit  interface{}
}

type GetTagCountByRangeRow struct {
	Text  string
	Count int64
}

func (q *Queries) GetTagCountByRange(ctx context.Context, arg GetTagCountByRangeParams) ([]GetTagCountByRangeRow, error) {
	rows, err := q.query(ctx, q.getTagCountByRangeStmt, GetTagCountByRange,
		arg.Start,
		arg.End,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTagCountByRangeRow
	for rows.Next() {
		var i GetTagCountByRangeRow
		if err := rows.Scan(&i.Text, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetTagCountByTag = `-- name: GetTagCountByTag :one
SELECT tag_count.tag_id, tag_count.total FROM tag_count 
JOIN tags ON tags.tag_id = tag_count.tag_id
WHERE tags.text == (?1)
`

func (q *Queries) GetTagCountByTag(ctx context.Context, tag string) (TagCount, error) {
	row := q.queryRow(ctx, q.getTagCountByTagStmt, GetTagCountByTag, tag)
	var i TagCount
	err := row.Scan(&i.TagID, &i.Total)
	return i, err
}

const GetTagID = `-- name: GetTagID :one
SELECT tag_id, text FROM tags WHERE text == (?1)
`

func (q *Queries) GetTagID(ctx context.Context, tag string) (Tag, error) {
	row := q.queryRow(ctx, q.getTagIDStmt, GetTagID, tag)
	var i Tag
	err := row.Scan(&i.TagID, &i.Text)
	return i, err
}

const GetTagsFromArchiveID = `-- name: GetTagsFromArchiveID :many
SELECT tags.text FROM tags 
	INNER JOIN tag_map ON tags.tag_id = tag_map.tag_id 
WHERE tag_map.archive_id == (?1)
`

func (q *Queries) GetTagsFromArchiveID(ctx context.Context, archiveID int64) ([]string, error) {
	rows, err := q.query(ctx, q.getTagsFromArchiveIDStmt, GetTagsFromArchiveID, archiveID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var text string
		if err := rows.Scan(&text); err != nil {
			return nil, err
		}
		items = append(items, text)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetTimestamps = `-- name: GetTimestamps :one
SELECT archive_id, date_modified, date_imported, date_created FROM archive_timestamps WHERE archive_id == (?1)
`

func (q *Queries) GetTimestamps(ctx context.Context, archiveID int64) (ArchiveTimestamp, error) {
	row := q.queryRow(ctx, q.getTimestampsStmt, GetTimestamps, archiveID)
	var i ArchiveTimestamp
	err := row.Scan(
		&i.ArchiveID,
		&i.DateModified,
		&i.DateImported,
		&i.DateCreated,
	)
	return i, err
}

const NewEntry = `-- name: NewEntry :exec
INSERT INTO archive (path, extension) VALUES (?1, ?2)
`

type NewEntryParams struct {
	Path      string
	Extension string
}

func (q *Queries) NewEntry(ctx context.Context, arg NewEntryParams) error {
	_, err := q.exec(ctx, q.newEntryStmt, NewEntry, arg.Path, arg.Extension)
	return err
}

const NewTag = `-- name: NewTag :exec
INSERT INTO tags (text) VALUES (?1)
`

func (q *Queries) NewTag(ctx context.Context, tag string) error {
	_, err := q.exec(ctx, q.newTagStmt, NewTag, tag)
	return err
}

const RemoveTag = `-- name: RemoveTag :exec
DELETE FROM tag_map
	WHERE tag_map.archive_id == (?1) AND
	tag_map.tag_id IN 
		(SELECT tags.tag_id FROM tags 
			INNER JOIN tag_map ON tags.tag_id = tag_map.tag_id 
				WHERE tags.text == (?2))
`

type RemoveTagParams struct {
	ArchiveID int64
	Text      string
}

func (q *Queries) RemoveTag(ctx context.Context, arg RemoveTagParams) error {
	_, err := q.exec(ctx, q.removeTagStmt, RemoveTag, arg.ArchiveID, arg.Text)
	return err
}

const RemoveTagsFromArchiveID = `-- name: RemoveTagsFromArchiveID :exec
DELETE FROM tag_map WHERE archive_id == (?1)
`

func (q *Queries) RemoveTagsFromArchiveID(ctx context.Context, archiveID int64) error {
	_, err := q.exec(ctx, q.removeTagsFromArchiveIDStmt, RemoveTagsFromArchiveID, archiveID)
	return err
}

const SearchTag = `-- name: SearchTag :many
SELECT archive.id, tags.tag_id, tags.text FROM tags 
	INNER JOIN tag_map ON tag_map.tag_id = tags.tag_id
	INNER JOIN archive ON archive.id = tag_map.archive_id
WHERE tags.text == (?1)
`

type SearchTagRow struct {
	ID    int64
	TagID int64
	Text  string
}

func (q *Queries) SearchTag(ctx context.Context, tag string) ([]SearchTagRow, error) {
	rows, err := q.query(ctx, q.searchTagStmt, SearchTag, tag)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchTagRow
	for rows.Next() {
		var i SearchTagRow
		if err := rows.Scan(&i.ID, &i.TagID, &i.Text); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SetHashes = `-- name: SetHashes :exec
INSERT OR REPLACE INTO hashes_chksum 
	(archive_id, md5, sha1, sha256) 
VALUES (?1, ?2, ?3, ?4)
`

type SetHashesParams struct {
	ArchiveID int64
	Md5       []byte
	Sha1      []byte
	Sha256    []byte
}

func (q *Queries) SetHashes(ctx context.Context, arg SetHashesParams) error {
	_, err := q.exec(ctx, q.setHashesStmt, SetHashes,
		arg.ArchiveID,
		arg.Md5,
		arg.Sha1,
		arg.Sha256,
	)
	return err
}

const SetMetadata = `-- name: SetMetadata :exec
INSERT OR REPLACE INTO "archive_metadata"
	(archive_id, file_size, file_mimetype, media_width, media_height, media_orientation)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
`

type SetMetadataParams struct {
	ArchiveID        int64
	FileSize         int64
	FileMimetype     sql.NullString
	MediaWidth       sql.NullInt64
	MediaHeight      sql.NullInt64
	MediaOrientation sql.NullString
}

func (q *Queries) SetMetadata(ctx context.Context, arg SetMetadataParams) error {
	_, err := q.exec(ctx, q.setMetadataStmt, SetMetadata,
		arg.ArchiveID,
		arg.FileSize,
		arg.FileMimetype,
		arg.MediaWidth,
		arg.MediaHeight,
		arg.MediaOrientation,
	)
	return err
}

const SetPerceptualHash = `-- name: SetPerceptualHash :exec
INSERT OR REPLACE INTO hashes_perceptual
	(archive_id, hash_type, hash)
VALUES (?1, ?2, ?3)
`

type SetPerceptualHashParams struct {
	ArchiveID int64
	HashType  string
	Hash      int64
}

func (q *Queries) SetPerceptualHash(ctx context.Context, arg SetPerceptualHashParams) error {
	_, err := q.exec(ctx, q.setPerceptualHashStmt, SetPerceptualHash, arg.ArchiveID, arg.HashType, arg.Hash)
	return err
}

const SetTag = `-- name: SetTag :exec
INSERT INTO tag_map 
	(archive_id, tag_id)
VALUES(?1, (?2))
`

type SetTagParams struct {
	ArchiveID int64
	TagID     interface{}
}

func (q *Queries) SetTag(ctx context.Context, arg SetTagParams) error {
	_, err := q.exec(ctx, q.setTagStmt, SetTag, arg.ArchiveID, arg.TagID)
	return err
}

const SetTimestamps = `-- name: SetTimestamps :exec
INSERT OR REPLACE INTO archive_timestamps 
	(archive_id, date_modified, date_imported, date_created)
VALUES (?1, ?2, ?3, ?4)
`

type SetTimestampsParams struct {
	ArchiveID    int64
	DateModified int64
	DateImported int64
	DateCreated  int64
}

func (q *Queries) SetTimestamps(ctx context.Context, arg SetTimestampsParams) error {
	_, err := q.exec(ctx, q.setTimestampsStmt, SetTimestamps,
		arg.ArchiveID,
		arg.DateModified,
		arg.DateImported,
		arg.DateCreated,
	)
	return err
}
