// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package archive

import (
	"context"
)

type Querier interface {
	AssignTag(ctx context.Context, arg AssignTagParams) error
	DeleteEntry(ctx context.Context, archiveID int64) error
	DeleteTag(ctx context.Context, tag string) error
	DeleteTagAlias(ctx context.Context, tag string) error
	DeleteTagMap(ctx context.Context, tagID int64) error
	GetEntry(ctx context.Context, archiveID int64) (Archive, error)
	GetEntryPath(ctx context.Context, archiveID int64) (GetEntryPathRow, error)
	GetHashes(ctx context.Context, archiveID int64) (HashesChksum, error)
	GetMetadata(ctx context.Context, archiveID int64) (ArchiveMetadata, error)
	GetMostRecentArchiveID(ctx context.Context) (int64, error)
	GetMostRecentTagID(ctx context.Context) (int64, error)
	GetPagesByDateCreated(ctx context.Context, arg GetPagesByDateCreatedParams) ([]Archive, error)
	GetPagesByDateCreatedDescending(ctx context.Context, arg GetPagesByDateCreatedDescendingParams) ([]Archive, error)
	GetPagesByDateImportedAscending(ctx context.Context, arg GetPagesByDateImportedAscendingParams) ([]Archive, error)
	GetPagesByDateImportedDecending(ctx context.Context, arg GetPagesByDateImportedDecendingParams) ([]Archive, error)
	GetPagesByDateModifiedAscending(ctx context.Context, arg GetPagesByDateModifiedAscendingParams) ([]Archive, error)
	GetPagesByDateModifiedDescending(ctx context.Context, arg GetPagesByDateModifiedDescendingParams) ([]Archive, error)
	GetPerceptualHash(ctx context.Context, arg GetPerceptualHashParams) (int64, error)
	GetTagCountByList(ctx context.Context, archiveIds []int64) ([]GetTagCountByListRow, error)
	GetTagCountByRange(ctx context.Context, arg GetTagCountByRangeParams) ([]GetTagCountByRangeRow, error)
	GetTagCountByTag(ctx context.Context, tag string) (TagCount, error)
	GetTagID(ctx context.Context, tag string) (Tag, error)
	GetTagsFromArchiveID(ctx context.Context, archiveID int64) ([]string, error)
	GetTimestamps(ctx context.Context, archiveID int64) (ArchiveTimestamp, error)
	NewEntry(ctx context.Context, arg NewEntryParams) error
	NewTag(ctx context.Context, tag string) error
	NewTagAlias(ctx context.Context, arg NewTagAliasParams) error
	RemoveTag(ctx context.Context, arg RemoveTagParams) error
	RemoveTagsFromArchiveID(ctx context.Context, archiveID int64) error
	ResolveTagAlias(ctx context.Context, aliasTag string) (ResolveTagAliasRow, error)
	ResolveTagAliasList(ctx context.Context, aliasTags []string) ([]ResolveTagAliasListRow, error)
	SearchTag(ctx context.Context, tag string) ([]SearchTagRow, error)
	SearchTagsByListDateCreated(ctx context.Context, arg SearchTagsByListDateCreatedParams) ([]SearchTagsByListDateCreatedRow, error)
	SearchTagsByListDateImported(ctx context.Context, arg SearchTagsByListDateImportedParams) ([]SearchTagsByListDateImportedRow, error)
	SearchTagsByListDateModified(ctx context.Context, arg SearchTagsByListDateModifiedParams) ([]SearchTagsByListDateModifiedRow, error)
	SetHashes(ctx context.Context, arg SetHashesParams) error
	SetMetadata(ctx context.Context, arg SetMetadataParams) error
	SetPerceptualHash(ctx context.Context, arg SetPerceptualHashParams) error
	SetTimestamps(ctx context.Context, arg SetTimestampsParams) error
}

var _ Querier = (*Queries)(nil)
