// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package archive

import (
	"context"
)

type Querier interface {
	DeleteEntry(ctx context.Context, archiveID int64) error
	DeleteTag(ctx context.Context, tag string) error
	DeleteTagMap(ctx context.Context, tagID int64) error
	GetEntry(ctx context.Context, archiveID int64) (Archive, error)
	GetEntryPath(ctx context.Context, archiveID int64) (GetEntryPathRow, error)
	GetHashes(ctx context.Context, archiveID int64) (HashesChksum, error)
	GetMostRecentArchiveID(ctx context.Context) (int64, error)
	GetMostRecentTagID(ctx context.Context) (int64, error)
	GetPerceptualHash(ctx context.Context, arg GetPerceptualHashParams) (int64, error)
	GetTagCount(ctx context.Context, tag string) (TagCount, error)
	GetTagID(ctx context.Context, tag string) (Tag, error)
	GetTagRange(ctx context.Context, arg GetTagRangeParams) ([]GetTagRangeRow, error)
	GetTagsFromArchiveID(ctx context.Context, archiveID int64) ([]string, error)
	GetTimestamps(ctx context.Context, archiveID int64) (ArchiveTimestamp, error)
	NewEntry(ctx context.Context, arg NewEntryParams) error
	NewTag(ctx context.Context, tag string) error
	RemoveTag(ctx context.Context, arg RemoveTagParams) error
	RemoveTagsFromArchiveID(ctx context.Context, archiveID int64) error
	SearchTag(ctx context.Context, tag string) ([]SearchTagRow, error)
	SetHashes(ctx context.Context, arg SetHashesParams) error
	SetPerceptualHash(ctx context.Context, arg SetPerceptualHashParams) error
	SetTag(ctx context.Context, arg SetTagParams) error
	SetTimestamps(ctx context.Context, arg SetTimestampsParams) error
}

var _ Querier = (*Queries)(nil)
