// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	GetEntry(ctx context.Context, archiveID int64) (Archive, error)
	GetHashes(ctx context.Context, archiveID int64) (Hash, error)
	GetMostRecentArchiveID(ctx context.Context) (int64, error)
	GetTags(ctx context.Context, archiveID int64) ([]string, error)
	GetTimestamps(ctx context.Context, archiveID int64) (Timestamp, error)
	NewEntry(ctx context.Context, arg NewEntryParams) error
	NewTag(ctx context.Context, tag string) error
	RemoveTag(ctx context.Context, tag string) error
	RemoveTagMap(ctx context.Context, text string) error
	SearchTag(ctx context.Context, tag string) (Tag, error)
	SetHashes(ctx context.Context, arg SetHashesParams) error
	SetTag(ctx context.Context, arg SetTagParams) error
	SetTimestamps(ctx context.Context, arg SetTimestampsParams) error
}

var _ Querier = (*Queries)(nil)
