// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: sqlite-query.sql

package db

import (
	"context"
	"database/sql"
)

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE text == (?1)
`

func (q *Queries) DeleteTag(ctx context.Context, tag string) error {
	_, err := q.db.ExecContext(ctx, deleteTag, tag)
	return err
}

const deleteTagMap = `-- name: DeleteTagMap :exec
DELETE FROM tagmap WHERE tag_id == (?1)
`

func (q *Queries) DeleteTagMap(ctx context.Context, tagID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTagMap, tagID)
	return err
}

const getEntry = `-- name: GetEntry :one
SELECT id, path, extension FROM archive WHERE id == (?1)
`

func (q *Queries) GetEntry(ctx context.Context, archiveID int64) (Archive, error) {
	row := q.db.QueryRowContext(ctx, getEntry, archiveID)
	var i Archive
	err := row.Scan(&i.ID, &i.Path, &i.Extension)
	return i, err
}

const getEntryPath = `-- name: GetEntryPath :one
SELECT path, extension FROM archive WHERE id == (?1)
`

type GetEntryPathRow struct {
	Path      string
	Extension sql.NullString
}

func (q *Queries) GetEntryPath(ctx context.Context, archiveID int64) (GetEntryPathRow, error) {
	row := q.db.QueryRowContext(ctx, getEntryPath, archiveID)
	var i GetEntryPathRow
	err := row.Scan(&i.Path, &i.Extension)
	return i, err
}

const getHashes = `-- name: GetHashes :one
SELECT archive_id, md5, sha1, sha256 FROM hashes WHERE archive_id == (?1)
`

func (q *Queries) GetHashes(ctx context.Context, archiveID int64) (Hash, error) {
	row := q.db.QueryRowContext(ctx, getHashes, archiveID)
	var i Hash
	err := row.Scan(
		&i.ArchiveID,
		&i.Md5,
		&i.Sha1,
		&i.Sha256,
	)
	return i, err
}

const getMostRecentArchiveID = `-- name: GetMostRecentArchiveID :one
SELECT id FROM archive WHERE id = (SELECT MAX(ID)  FROM archive)
`

func (q *Queries) GetMostRecentArchiveID(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMostRecentArchiveID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getTagID = `-- name: GetTagID :one
SELECT tag_id, text FROM tags WHERE text == (?1)
`

func (q *Queries) GetTagID(ctx context.Context, tag string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagID, tag)
	var i Tag
	err := row.Scan(&i.TagID, &i.Text)
	return i, err
}

const getTagsFromArchiveID = `-- name: GetTagsFromArchiveID :many
SELECT tags.text FROM tags 
	INNER JOIN tagmap ON tags.tag_id = tagmap.tag_id 
WHERE tagmap.archive_id == (?1)
`

func (q *Queries) GetTagsFromArchiveID(ctx context.Context, archiveID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getTagsFromArchiveID, archiveID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var text string
		if err := rows.Scan(&text); err != nil {
			return nil, err
		}
		items = append(items, text)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTimestamps = `-- name: GetTimestamps :one
SELECT archive_id, date_modified, date_imported FROM timestamps WHERE archive_id == (?1)
`

func (q *Queries) GetTimestamps(ctx context.Context, archiveID int64) (Timestamp, error) {
	row := q.db.QueryRowContext(ctx, getTimestamps, archiveID)
	var i Timestamp
	err := row.Scan(&i.ArchiveID, &i.DateModified, &i.DateImported)
	return i, err
}

const newEntry = `-- name: NewEntry :exec
INSERT INTO archive (path, extension) VALUES (?1, ?2)
RETURNING id
`

type NewEntryParams struct {
	Path      string
	Extension sql.NullString
}

func (q *Queries) NewEntry(ctx context.Context, arg NewEntryParams) error {
	_, err := q.db.ExecContext(ctx, newEntry, arg.Path, arg.Extension)
	return err
}

const newTag = `-- name: NewTag :exec
INSERT OR IGNORE INTO tags (text) VALUES (?1)
`

func (q *Queries) NewTag(ctx context.Context, tag string) error {
	_, err := q.db.ExecContext(ctx, newTag, tag)
	return err
}

const removeTag = `-- name: RemoveTag :exec
DELETE FROM tagmap
	WHERE tagmap.archive_id == (?1) AND
	tagmap.tag_id IN 
		(SELECT tags.tag_id FROM tags 
			INNER JOIN tagmap ON tags.tag_id = tagmap.tag_id 
				WHERE tags.text == (?2))
`

type RemoveTagParams struct {
	ArchiveID int64
	Text      string
}

func (q *Queries) RemoveTag(ctx context.Context, arg RemoveTagParams) error {
	_, err := q.db.ExecContext(ctx, removeTag, arg.ArchiveID, arg.Text)
	return err
}

const searchTag = `-- name: SearchTag :many
SELECT archive.id, tags.tag_id, tags.text FROM tags 
	INNER JOIN tagmap ON tagmap.tag_id = tags.tag_id
	INNER JOIN archive ON archive.id = tagmap.archive_id
WHERE tags.text == (?1)
`

type SearchTagRow struct {
	ID    int64
	TagID int64
	Text  string
}

func (q *Queries) SearchTag(ctx context.Context, tag string) ([]SearchTagRow, error) {
	rows, err := q.db.QueryContext(ctx, searchTag, tag)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchTagRow
	for rows.Next() {
		var i SearchTagRow
		if err := rows.Scan(&i.ID, &i.TagID, &i.Text); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setHashes = `-- name: SetHashes :exec
INSERT OR REPLACE INTO hashes 
	(archive_id, md5, sha1, sha256) 
VALUES (?1, ?2, ?3, ?4)
`

type SetHashesParams struct {
	ArchiveID int64
	Md5       []byte
	Sha1      []byte
	Sha256    []byte
}

func (q *Queries) SetHashes(ctx context.Context, arg SetHashesParams) error {
	_, err := q.db.ExecContext(ctx, setHashes,
		arg.ArchiveID,
		arg.Md5,
		arg.Sha1,
		arg.Sha256,
	)
	return err
}

const setTag = `-- name: SetTag :exec
INSERT OR IGNORE INTO tagmap 
	(archive_id, tag_id)
VALUES(?1, (SELECT tag_id FROM tags WHERE text = (?2)))
`

type SetTagParams struct {
	ArchiveID int64
	Tag       string
}

func (q *Queries) SetTag(ctx context.Context, arg SetTagParams) error {
	_, err := q.db.ExecContext(ctx, setTag, arg.ArchiveID, arg.Tag)
	return err
}

const setTimestamps = `-- name: SetTimestamps :exec
INSERT OR REPLACE INTO timestamps 
	(archive_id, date_modified, date_imported)
VALUES (?1, ?2, ?3)
`

type SetTimestampsParams struct {
	ArchiveID    int64
	DateModified string
	DateImported string
}

func (q *Queries) SetTimestamps(ctx context.Context, arg SetTimestampsParams) error {
	_, err := q.db.ExecContext(ctx, setTimestamps, arg.ArchiveID, arg.DateModified, arg.DateImported)
	return err
}
