// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package thumbnail

type Thumbnail struct {
	ArchiveID int64
	HasJpeg   int64
	HasWebp   int64
}

type ThumbnailBlurhash struct {
	ArchiveID int64
	Hash      string
}

type ThumbnailJpeg struct {
	ArchiveID int64
	Small     []byte
	Medium    []byte
	Large     []byte
}
