// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: thumbnail_query.sql

package thumbnail

import (
	"context"
)

const GetJpegMedigum = `-- name: GetJpegMedigum :one
SELECT medium FROM "thumbnail_jpeg" WHERE archive_id == (?1)
`

func (q *Queries) GetJpegMedigum(ctx context.Context, archiveID int64) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, GetJpegMedigum, archiveID)
	var medium []byte
	err := row.Scan(&medium)
	return medium, err
}

const GetJpeglarge = `-- name: GetJpeglarge :one
SELECT large FROM "thumbnail_jpeg" WHERE archive_id == (?1)
`

func (q *Queries) GetJpeglarge(ctx context.Context, archiveID int64) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, GetJpeglarge, archiveID)
	var large []byte
	err := row.Scan(&large)
	return large, err
}

const GetJpegsmall = `-- name: GetJpegsmall :one
SELECT small FROM "thumbnail_jpeg" WHERE archive_id == (?1)
`

func (q *Queries) GetJpegsmall(ctx context.Context, archiveID int64) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, GetJpegsmall, archiveID)
	var small []byte
	err := row.Scan(&small)
	return small, err
}

const GetWebpMedigum = `-- name: GetWebpMedigum :one
SELECT medium FROM "thumbnail_jpeg" WHERE archive_id == (?1)
`

func (q *Queries) GetWebpMedigum(ctx context.Context, archiveID int64) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, GetWebpMedigum, archiveID)
	var medium []byte
	err := row.Scan(&medium)
	return medium, err
}

const GetWebplarge = `-- name: GetWebplarge :one
SELECT large FROM "thumbnail_jpeg" WHERE archive_id == (?1)
`

func (q *Queries) GetWebplarge(ctx context.Context, archiveID int64) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, GetWebplarge, archiveID)
	var large []byte
	err := row.Scan(&large)
	return large, err
}

const GetWebpsmall = `-- name: GetWebpsmall :one
SELECT small FROM "thumbnail_jpeg" WHERE archive_id == (?1)
`

func (q *Queries) GetWebpsmall(ctx context.Context, archiveID int64) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, GetWebpsmall, archiveID)
	var small []byte
	err := row.Scan(&small)
	return small, err
}

const NewJpeg = `-- name: NewJpeg :exec
INSERT INTO "thumbnail_jpeg" (archive_id, small, medium, large) VALUES (?1, ?2, ?3, ?4)
`

type NewJpegParams struct {
	ArchiveID int64
	Small     []byte
	Medium    []byte
	Large     []byte
}

func (q *Queries) NewJpeg(ctx context.Context, arg NewJpegParams) error {
	_, err := q.db.ExecContext(ctx, NewJpeg,
		arg.ArchiveID,
		arg.Small,
		arg.Medium,
		arg.Large,
	)
	return err
}

const NewThumbnail = `-- name: NewThumbnail :exec
INSERT INTO "thumbnail" (archive_id, has_jpeg, has_webp) VALUES (?1, 0, 0)
`

func (q *Queries) NewThumbnail(ctx context.Context, archiveID int64) error {
	_, err := q.db.ExecContext(ctx, NewThumbnail, archiveID)
	return err
}

const NewWebp = `-- name: NewWebp :exec
INSERT INTO "thumbnail_webp" (archive_id, small, medium, large) VALUES (?1, ?2, ?3, ?4)
`

type NewWebpParams struct {
	ArchiveID int64
	Small     []byte
	Medium    []byte
	Large     []byte
}

func (q *Queries) NewWebp(ctx context.Context, arg NewWebpParams) error {
	_, err := q.db.ExecContext(ctx, NewWebp,
		arg.ArchiveID,
		arg.Small,
		arg.Medium,
		arg.Large,
	)
	return err
}
