# This workflow will run all tests in moonpool
name: Testing

on:
  push:
    paths:
      - '**.go'   # golang
      - '**.mod'  # golang
      - '**.sum'  # golang
      - '**.sql'  # sqlc
      - '**.yaml' # sqlc
      - '**.yml'  # github actions
  pull_request:
   branches:
   - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.x'

    - name: Go Tidy
      run: go mod tidy && git diff --exit-code

    - name: Go Mod
      run: go mod download

    - name: Go Mod Verify
      run: go mod verify

    - name: Install dependencies
      run: sudo apt install libwebp-dev ffmpeg

    - name: Go Format
      run: gofmt -s -w . && git diff --exit-code

    - name: Go Vet
      run: go vet ./...
    
    - name: Go Build
      run: go build -v -a -installsuffix cgo -ldflags '-s' ./...

    - name: Go Test
      run: go test -v -count=1 -race -shuffle=on ./...
      
